### ISSUE TITLE
Doesn't work together with markdown-3.0

### ISSUE THREAD

**Issue by y0va** [rufuspollock/markdown2latex#3]
With markdown-3.0 inlinePatterns seems not to be iterable anymore with iteritems():

```
$ pip install markdown
Collecting markdown
  Using cached https://files.pythonhosted.org/packages/7a/fd/e22357c299e93c0bc11ec8ba54e79f98dd568e09adfe9b39d6852c744938/Markdown-3.0-py2.py3-none-any.whl
Installing collected packages: markdown
Successfully installed markdown-3.0
~/coding/markdown2latex$ ./mdx_latex.py recommendations.md
Traceback (most recent call last):
  File "./mdx_latex.py", line 700, in <module>
    main()
  File "./mdx_latex.py", line 690, in main
    mkdn2latex.extendMarkdown(md, markdown.__dict__)
  File "./mdx_latex.py", line 133, in extendMarkdown
    for key, pat in self.md.inlinePatterns.iteritems():
AttributeError: 'Registry' object has no attribute 'iteritems'
```

**Comment by rufuspollock** [comment]
@y0va thanks - do you want to submit a PR for this?
